# Generated by Django 3.0.7 on 2020-07-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200712_0610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Out1',
            new_name='Out',
        ),
    ]
