# Generated by Django 3.0.7 on 2020-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200712_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='out',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
