# Generated by Django 3.0.7 on 2020-07-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_out_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out',
            name='In',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.In'),
        ),
        migrations.AlterField(
            model_name='out',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
