# Generated by Django 3.0.7 on 2020-07-14 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200715_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out',
            name='date_time',
        ),
        migrations.AddField(
            model_name='out',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='out',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
