# Generated by Django 3.0.7 on 2020-07-15 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out',
            name='date',
        ),
        migrations.AddField(
            model_name='out',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
