# Generated by Django 3.0.7 on 2020-07-15 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='out',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='out',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='out',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
