# Generated by Django 3.0.7 on 2020-08-20 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_out_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, default='', null=True)),
                ('type', models.IntegerField(choices=[(0, 'In'), (1, 'Out'), (2, 'In and Out')])),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
                ('person_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
    ]
