# Generated by Django 3.0.7 on 2020-08-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200820_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='In',
            new_name='Log',
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Log'},
        ),
        migrations.RenameField(
            model_name='out',
            old_name='In',
            new_name='log',
        ),
    ]
