# Generated by Django 3.0.7 on 2020-08-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200820_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='log',
            name='person_visitor',
        ),
        migrations.CreateModel(
            name='Log_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('tracing_code', models.CharField(max_length=100)),
                ('person_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Log_details'),
        ),
    ]
