# Generated by Django 3.0.7 on 2020-08-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_details',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Document_type'),
        ),
    ]
