# Generated by Django 3.0.7 on 2020-08-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_log_details_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_details',
            name='document_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Document_type'),
        ),
    ]
