# Generated by Django 3.0.7 on 2020-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200821_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
