# Generated by Django 3.0.7 on 2020-08-30 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200821_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_details',
            name='document_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AlterField(
            model_name='log_details',
            name='tracing_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
