# Generated by Django 3.0.7 on 2020-12-06 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_log_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date_now',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
