# Generated by Django 3.0.7 on 2020-08-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childb',
            name='a_ptr',
        ),
        migrations.RemoveField(
            model_name='childc',
            name='a_ptr',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='childB',
        ),
        migrations.DeleteModel(
            name='childC',
        ),
    ]
