# Generated by Django 3.0.7 on 2020-08-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gago',
            old_name='id',
            new_name='request_id',
        ),
    ]
