# Generated by Django 3.0.7 on 2020-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200819_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
