# Generated by Django 3.0.7 on 2020-08-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200819_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idD', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.A')),
            ],
        ),
        migrations.DeleteModel(
            name='Gago',
        ),
        migrations.CreateModel(
            name='childB',
            fields=[
                ('a_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.A')),
                ('idA', models.AutoField(primary_key=True, serialize=False)),
                ('nameB', models.CharField(default='', max_length=100)),
            ],
            bases=('home.a',),
        ),
        migrations.CreateModel(
            name='childC',
            fields=[
                ('a_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.A')),
                ('idC', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(default='', max_length=100)),
            ],
            bases=('home.a',),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
